export const countries = [ 
    {name: "Afghanistan", code: "AF"}, 
    {name: "land Islands", code: "AX"}, 
    {name: "Albania", code: "AL"}, 
    {name: "Algeria", code: "DZ"}, 
    {name: "American Samoa", code: "AS"}, 
    {name: "AndorrA", code: "AD"}, 
    {name: "Angola", code: "AO"}, 
    {name: "Anguilla", code: "AI"}, 
    {name: "Antarctica", code: "AQ"}, 
    {name: "Antigua and Barbuda", code: "AG"}, 
    {name: "Argentina", code: "AR"}, 
    {name: "Armenia", code: "AM"}, 
    {name: "Aruba", code: "AW"}, 
    {name: "Australia", code: "AU"}, 
    {name: "Austria", code: "AT"}, 
    {name: "Azerbaijan", code: "AZ"}, 
    {name: "Bahamas", code: "BS"}, 
    {name: "Bahrain", code: "BH"}, 
    {name: "Bangladesh", code: "BD"}, 
    {name: "Barbados", code: "BB"}, 
    {name: "Belarus", code: "BY"}, 
    {name: "Belgium", code: "BE"}, 
    {name: "Belize", code: "BZ"}, 
    {name: "Benin", code: "BJ"}, 
    {name: "Bermuda", code: "BM"}, 
    {name: "Bhutan", code: "BT"}, 
    {name: "Bolivia", code: "BO"}, 
    {name: "Bosnia and Herzegovina", code: "BA"}, 
    {name: "Botswana", code: "BW"}, 
    {name: "Bouvet Island", code: "BV"}, 
    {name: "Brazil", code: "BR"}, 
    {name: "British Indian Ocean Territory", code: "IO"}, 
    {name: "Brunei Darussalam", code: "BN"}, 
    {name: "Bulgaria", code: "BG"}, 
    {name: "Burkina Faso", code: "BF"}, 
    {name: "Burundi", code: "BI"}, 
    {name: "Cambodia", code: "KH"}, 
    {name: "Cameroon", code: "CM"}, 
    {name: "Canada", code: "CA"}, 
    {name: "Cape Verde", code: "CV"}, 
    {name: "Cayman Islands", code: "KY"}, 
    {name: "Central African Republic", code: "CF"}, 
    {name: "Chad", code: "TD"}, 
    {name: "Chile", code: "CL"}, 
    {name: "China", code: "CN"}, 
    {name: "Christmas Island", code: "CX"}, 
    {name: "Cocos (Keeling) Islands", code: "CC"}, 
    {name: "Colombia", code: "CO"}, 
    {name: "Comoros", code: "KM"}, 
    {name: "Congo", code: "CG"}, 
    {name: "Congo, The Democratic Republic of the", code: "CD"}, 
    {name: "Cook Islands", code: "CK"}, 
    {name: "Costa Rica", code: "CR"}, 
    {name: "Cote D'Ivoire", code: "CI"}, 
    {name: "Croatia", code: "HR"}, 
    {name: "Cuba", code: "CU"}, 
    {name: "Cyprus", code: "CY"}, 
    {name: "Czech Republic", code: "CZ"}, 
    {name: "Denmark", code: "DK"}, 
    {name: "Djibouti", code: "DJ"}, 
    {name: "Dominica", code: "DM"}, 
    {name: "Dominican Republic", code: "DO"}, 
    {name: "Ecuador", code: "EC"}, 
    {name: "Egypt", code: "EG"}, 
    {name: "El Salvador", code: "SV"}, 
    {name: "Equatorial Guinea", code: "GQ"}, 
    {name: "Eritrea", code: "ER"}, 
    {name: "Estonia", code: "EE"}, 
    {name: "Ethiopia", code: "ET"}, 
    {name: "Falkland Islands (Malvinas)", code: "FK"}, 
    {name: "Faroe Islands", code: "FO"}, 
    {name: "Fiji", code: "FJ"}, 
    {name: "Finland", code: "FI"}, 
    {name: "France", code: "FR"}, 
    {name: "French Guiana", code: "GF"}, 
    {name: "French Polynesia", code: "PF"}, 
    {name: "French Southern Territories", code: "TF"}, 
    {name: "Gabon", code: "GA"}, 
    {name: "Gambia", code: "GM"}, 
    {name: "Georgia", code: "GE"}, 
    {name: "Germany", code: "DE"}, 
    {name: "Ghana", code: "GH"}, 
    {name: "Gibraltar", code: "GI"}, 
    {name: "Greece", code: "GR"}, 
    {name: "Greenland", code: "GL"}, 
    {name: "Grenada", code: "GD"}, 
    {name: "Guadeloupe", code: "GP"}, 
    {name: "Guam", code: "GU"}, 
    {name: "Guatemala", code: "GT"}, 
    {name: "Guernsey", code: "GG"}, 
    {name: "Guinea", code: "GN"}, 
    {name: "Guinea-Bissau", code: "GW"}, 
    {name: "Guyana", code: "GY"}, 
    {name: "Haiti", code: "HT"}, 
    {name: "Heard Island and Mcdonald Islands", code: "HM"}, 
    {name: "Holy See (Vatican City State)", code: "VA"}, 
    {name: "Honduras", code: "HN"}, 
    {name: "Hong Kong", code: "HK"}, 
    {name: "Hungary", code: "HU"}, 
    {name: "Iceland", code: "IS"}, 
    {name: "India", code: "IN"}, 
    {name: "Indonesia", code: "ID"}, 
    {name: "Iran, Islamic Republic Of", code: "IR"}, 
    {name: "Iraq", code: "IQ"}, 
    {name: "Ireland", code: "IE"}, 
    {name: "Isle of Man", code: "IM"}, 
    {name: "Israel", code: "IL"}, 
    {name: "Italy", code: "IT"}, 
    {name: "Jamaica", code: "JM"}, 
    {name: "Japan", code: "JP"}, 
    {name: "Jersey", code: "JE"}, 
    {name: "Jordan", code: "JO"}, 
    {name: "Kazakhstan", code: "KZ"}, 
    {name: "Kenya", code: "KE"}, 
    {name: "Kiribati", code: "KI"}, 
    {name: "Korea, Democratic People'S Republic of", code: "KP"}, 
    {name: "Korea, Republic of", code: "KR"}, 
    {name: "Kuwait", code: "KW"}, 
    {name: "Kyrgyzstan", code: "KG"}, 
    {name: "Lao People'S Democratic Republic", code: "LA"}, 
    {name: "Latvia", code: "LV"}, 
    {name: "Lebanon", code: "LB"}, 
    {name: "Lesotho", code: "LS"}, 
    {name: "Liberia", code: "LR"}, 
    {name: "Libyan Arab Jamahiriya", code: "LY"}, 
    {name: "Liechtenstein", code: "LI"}, 
    {name: "Lithuania", code: "LT"}, 
    {name: "Luxembourg", code: "LU"}, 
    {name: "Macao", code: "MO"}, 
    {name: "Macedonia, The Former Yugoslav Republic of", code: "MK"}, 
    {name: "Madagascar", code: "MG"}, 
    {name: "Malawi", code: "MW"}, 
    {name: "Malaysia", code: "MY"}, 
    {name: "Maldives", code: "MV"}, 
    {name: "Mali", code: "ML"}, 
    {name: "Malta", code: "MT"}, 
    {name: "Marshall Islands", code: "MH"}, 
    {name: "Martinique", code: "MQ"}, 
    {name: "Mauritania", code: "MR"}, 
    {name: "Mauritius", code: "MU"}, 
    {name: "Mayotte", code: "YT"}, 
    {name: "Mexico", code: "MX"}, 
    {name: "Micronesia, Federated States of", code: "FM"}, 
    {name: "Moldova, Republic of", code: "MD"}, 
    {name: "Monaco", code: "MC"}, 
    {name: "Mongolia", code: "MN"}, 
    {name: "Montenegro", code: "ME"},
    {name: "Montserrat", code: "MS"},
    {name: "Morocco", code: "MA"}, 
    {name: "Mozambique", code: "MZ"}, 
    {name: "Myanmar", code: "MM"}, 
    {name: "Namibia", code: "NA"}, 
    {name: "Nauru", code: "NR"}, 
    {name: "Nepal", code: "NP"}, 
    {name: "Netherlands", code: "NL"}, 
    {name: "Netherlands Antilles", code: "AN"}, 
    {name: "New Caledonia", code: "NC"}, 
    {name: "New Zealand", code: "NZ"}, 
    {name: "Nicaragua", code: "NI"}, 
    {name: "Niger", code: "NE"}, 
    {name: "Nigeria", code: "NG"}, 
    {name: "Niue", code: "NU"}, 
    {name: "Norfolk Island", code: "NF"}, 
    {name: "Northern Mariana Islands", code: "MP"}, 
    {name: "Norway", code: "NO"}, 
    {name: "Oman", code: "OM"}, 
    {name: "Pakistan", code: "PK"}, 
    {name: "Palau", code: "PW"}, 
    {name: "Palestinian Territory, Occupied", code: "PS"}, 
    {name: "Panama", code: "PA"}, 
    {name: "Papua New Guinea", code: "PG"}, 
    {name: "Paraguay", code: "PY"}, 
    {name: "Peru", code: "PE"}, 
    {name: "Philippines", code: "PH"}, 
    {name: "Pitcairn", code: "PN"}, 
    {name: "Poland", code: "PL"}, 
    {name: "Portugal", code: "PT"}, 
    {name: "Puerto Rico", code: "PR"}, 
    {name: "Qatar", code: "QA"}, 
    {name: "Reunion", code: "RE"}, 
    {name: "Romania", code: "RO"}, 
    {name: "Russian Federation", code: "RU"}, 
    {name: "RWANDA", code: "RW"}, 
    {name: "Saint Helena", code: "SH"}, 
    {name: "Saint Kitts and Nevis", code: "KN"}, 
    {name: "Saint Lucia", code: "LC"}, 
    {name: "Saint Pierre and Miquelon", code: "PM"}, 
    {name: "Saint Vincent and the Grenadines", code: "VC"}, 
    {name: "Samoa", code: "WS"}, 
    {name: "San Marino", code: "SM"}, 
    {name: "Sao Tome and Principe", code: "ST"}, 
    {name: "Saudi Arabia", code: "SA"}, 
    {name: "Senegal", code: "SN"}, 
    {name: "Serbia", code: "RS"}, 
    {name: "Seychelles", code: "SC"}, 
    {name: "Sierra Leone", code: "SL"}, 
    {name: "Singapore", code: "SG"}, 
    {name: "Slovakia", code: "SK"}, 
    {name: "Slovenia", code: "SI"}, 
    {name: "Solomon Islands", code: "SB"}, 
    {name: "Somalia", code: "SO"}, 
    {name: "South Africa", code: "ZA"}, 
    {name: "South Georgia and the South Sandwich Islands", code: "GS"}, 
    {name: "Spain", code: "ES"}, 
    {name: "Sri Lanka", code: "LK"}, 
    {name: "Sudan", code: "SD"}, 
    {name: "Suriname", code: "SR"}, 
    {name: "Svalbard and Jan Mayen", code: "SJ"}, 
    {name: "Swaziland", code: "SZ"}, 
    {name: "Sweden", code: "SE"}, 
    {name: "Switzerland", code: "CH"}, 
    {name: "Syrian Arab Republic", code: "SY"}, 
    {name: "Taiwan, Province of China", code: "TW"}, 
    {name: "Tajikistan", code: "TJ"}, 
    {name: "Tanzania, United Republic of", code: "TZ"}, 
    {name: "Thailand", code: "TH"}, 
    {name: "Timor-Leste", code: "TL"}, 
    {name: "Togo", code: "TG"}, 
    {name: "Tokelau", code: "TK"}, 
    {name: "Tonga", code: "TO"}, 
    {name: "Trinidad and Tobago", code: "TT"}, 
    {name: "Tunisia", code: "TN"}, 
    {name: "Turkey", code: "TR"}, 
    {name: "Turkmenistan", code: "TM"}, 
    {name: "Turks and Caicos Islands", code: "TC"}, 
    {name: "Tuvalu", code: "TV"}, 
    {name: "Uganda", code: "UG"}, 
    {name: "Ukraine", code: "UA"}, 
    {name: "United Arab Emirates", code: "AE"}, 
    {name: "United Kingdom", code: "GB"}, 
    {name: "United States", code: "US"}, 
    {name: "United States Minor Outlying Islands", code: "UM"}, 
    {name: "Uruguay", code: "UY"}, 
    {name: "Uzbekistan", code: "UZ"}, 
    {name: "Vanuatu", code: "VU"}, 
    {name: "Venezuela", code: "VE"}, 
    {name: "Viet Nam", code: "VN"}, 
    {name: "Virgin Islands, British", code: "VG"}, 
    {name: "Virgin Islands, U.S.", code: "VI"}, 
    {name: "Wallis and Futuna", code: "WF"}, 
    {name: "Western Sahara", code: "EH"}, 
    {name: "Yemen", code: "YE"}, 
    {name: "Zambia", code: "ZM"}, 
    {name: "Zimbabwe", code: "ZW"} 
]

export const states = [
    {
      state_name: 'Andaman and Nicobar Islands',
      state_code: '35',
      state_shortcode: 'AN',
    },
    { state_name: 'Andhra Pradesh', state_code: '28', state_shortcode: 'AP' },
    {
      state_name: 'Andhra Pradesh (New)',
      state_code: '37',
      state_shortcode: 'AD',
    },
    {
      state_name: 'Arunachal Pradesh',
      state_code: '12',
      state_shortcode: 'AR',
    },
    { state_name: 'Assam', state_code: '18', state_shortcode: 'AS' },
    { state_name: 'Bihar', state_code: '10', state_shortcode: 'BH' },
    { state_name: 'Chandigarh', state_code: '04', state_shortcode: 'CH' },
    { state_name: 'Chattisgarh', state_code: '22', state_shortcode: 'CT' },
    {
      state_name: 'Dadra and Nagar Haveli',
      state_code: '26',
      state_shortcode: 'DN',
    },
    { state_name: 'Daman and Diu', state_code: '25', state_shortcode: 'DD' },
    { state_name: 'Delhi', state_code: '07', state_shortcode: 'DL' },
    { state_name: 'Goa', state_code: '30', state_shortcode: 'GA' },
    { state_name: 'Gujarat', state_code: '24', state_shortcode: 'GJ' },
    { state_name: 'Haryana', state_code: '06', state_shortcode: 'HR' },
    { state_name: 'Himachal Pradesh', state_code: '02', state_shortcode: 'HP' },
    {
      state_name: 'Jammu and Kashmir',
      state_code: '01',
      state_shortcode: 'JK',
    },
    { state_name: 'Jharkhand', state_code: '20', state_shortcode: 'JH' },
    { state_name: 'Karnataka', state_code: '29', state_shortcode: 'KA' },
    { state_name: 'Kerala', state_code: '32', state_shortcode: 'KL' },
    { state_name: 'Ladakh', state_code: '38', state_shortcode: 'LA' },
    {
      state_name: 'Lakshadweep Islands',
      state_code: '31',
      state_shortcode: 'LD',
    },
    { state_name: 'Madhya Pradesh', state_code: '23', state_shortcode: 'MP' },
    { state_name: 'Maharashtra', state_code: '27', state_shortcode: 'MH' },
    { state_name: 'Manipur', state_code: '14', state_shortcode: 'MN' },
    { state_name: 'Meghalaya', state_code: '17', state_shortcode: 'ME' },
    { state_name: 'Mizoram', state_code: '15', state_shortcode: 'MI' },
    { state_name: 'Nagaland', state_code: '13', state_shortcode: 'NL' },
    { state_name: 'Odisha', state_code: '21', state_shortcode: 'OR' },
    { state_name: 'Pondicherry', state_code: '34', state_shortcode: 'PY' },
    { state_name: 'Punjab', state_code: '03', state_shortcode: 'PB' },
    { state_name: 'Rajasthan', state_code: '08', state_shortcode: 'RJ' },
    { state_name: 'Sikkim', state_code: '11', state_shortcode: 'SK' },
    { state_name: 'Tamil Nadu', state_code: '33', state_shortcode: 'TN' },
    { state_name: 'Telangana', state_code: '36', state_shortcode: 'TS' },
    { state_name: 'Tripura', state_code: '16', state_shortcode: 'TR' },
    { state_name: 'Uttar Pradesh', state_code: '09', state_shortcode: 'UP' },
    { state_name: 'Uttarakhand', state_code: '05', state_shortcode: 'UT' },
    { state_name: 'West Bengal', state_code: '19', state_shortcode: 'WB' },
  ];


export const measurementUnits = [
    {id:"", name:"Select Unit"},
    {id:"BAG", name:"Bag"},									
    {id:"BGS", name:"Bags"},
    {id:"BLS", name:"Bails"},
    {id:"BTL", name:"Bottles"},
    {id:"BOU", name:"Bou"},
    {id:"BOX", name:"Boxes"},
    {id:"BKL", name:"Buckles"},
    {id:"BLK", name:"Bulk"},
    {id:"BUN", name:"Bunches"},
    {id:"BDL", name:"Bundles"},
    {id:"CAN", name:"Cans"},
    {id:"CTS", name:"Carats"},
    {id:"CTN", name:"Cartons"},
    {id:"CAS", name:"Cases"},
    {id:"CMS", name:"Centimeter"},
    {id:"CHK", name:"Chauka"},
    {id:"CHI", name:"Chest"},
    {id:"CLS", name:"Coils"},
    {id:"COL", name:"Collies"},
    {id:"CRI", name:"Crates"},
    {id:"CCM", name:"Cubic Centimeter"},
    {id:"CFT", name:"Cubic Feet"},
    {id:"CIN", name:"Cubic Inches"},
    {id:"CBM", name:"Cubic Meter"},
    {id:"CQM", name:"Cubic Meters"},
    {id:"CYL", name:"Cylinder"},
    {id:"DAY", name:"Days"},
    {id:"SDM", name:"Decameter Square"},
    {id:"DOZ", name:"Dozen"},
    {id:"DRM", name:"Drums"},
    {id:"FTS", name:"Feet"},
    {id:"FLK", name:"Flasks"},									
    {id:"GMS", name:"Grams"},									
    {id:"GGR", name:"Great Gross"},
    {id:"TON", name:"Greate Britain Ton"},
    {id:"GRS", name:"Gross"},
    {id:"GYS", name:"Gross Yards"},
    {id:"HBK", name:"Habbuck"},
    {id:"HKS", name:"Hanks"},
    {id:"HRS", name:"Hours"},
    {id:"INC", name:"Inches"},
    {id:"IND", name:"Inch Dia"},
    {id:"INM", name:"Inch Meter"},
    {id:"JAR", name:"Jar"},
    {id:"JOB", name:"Job"},
    {id:"JTA", name:"Jotta"},
    {id:"KGS", name:"Kilograms"},
    {id:"KLR", name:"Kiloliter"},
    {id:"KMS", name:"Kilometers"},
    {id:"KW", name:"Kilowatt"},
    {id:"LTR", name:"Liters"},
    {id:"LIN", name:"Lines"},
    {id:"LOAD", name:"Load"},
    {id:"LOG", name:"Logs"},
    {id:"LOT", name:"Lots"},
    {id:"LS", name:"Lumpsum"},
    {id:"MTR", name:"Meter"},
    {id:"MTS", name:"Metric Ton"},
    {id:"MGS", name:"Milli Grams"},
    {id:"MLT", name:"Milli Litre"},
    {id:"MMT", name:"Milli Meter"},
    {id:"MO", name:"Month"},
    {id:"NOS", name:"Numbers"},
    {id:"ODD", name:"Odds"},
    {id:"OTH", name:"Others"},
    {id:"PKG", name:"Package"},
    {id:"PKT", name:"Packet"},
    {id:"PKD", name:"Peck - Dry Measure"},
    {id:"PAC", name:"Packs"},
    {id:"PAI", name:"Pails"},
    {id:"PRS", name:"Pairs"},
    {id:"PLT", name:"Pallets"},
    {id:"PCS", name:"Pieces"},
    {id:"LBS", name:"Pounds"},
    {id:"QTL", name:"Quintal"},
    {id:"REL", name:"Reels"},
    {id:"RIM", name:"RIM"},
    {id:"ROL", name:"Rolls"},
    {id:"RFT", name:"Running Feet"},
    {id:"SET", name:"Sets"},
    {id:"SHT", name:"Sheets"},
    {id:"SLB", name:"Slabs"},
    {id:"SQC", name:"Sqaure Centimeters"},
    {id:"SQF", name:"Sqaure Feet"},
    {id:"SQI", name:"Square Inches"},
    {id:"SQM", name:"Square Meter"},
    {id:"SQY", name:"Square Yards"},
    {id:"BLO", name:"Steel Blocks"},
    {id:"STR", name:"Strings"},
    {id:"TBL", name:"Tables"},
    {id:"TBS", name:"Tablets"},
    {id:"TGM", name:"Ten Gross"},
    {id:"THD", name:"Thousands"},
    {id:"TIN", name:"Tins"},
    {id:"TOL", name:"Tola"},
    {id:"TRK", name:"Trunk"},
    {id:"TUB", name:"Tubes"},
    {id:"UGS", name:"US Gallons"},
    {id:"UNT", name:"Units"},
    {id:"VLS", name:"Vials"},
    {id:"CSK", name:"Wooden Cases"},
    {id:"YDS", name:"Yards"},
    {id:"YO", name:"Year"},
]